version: '3'
services:
  mariadb:
    build: .
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=team1
      - MYSQL_HOST=localhost
      - MYSQL_USER=user
      - MYSQL_PASSWORD=team1
      - Projekti=1
